import { defineConfig } from 'vite';
import { resolve } from 'path';
import fs from 'fs';

// Plugin to copy static files (sw.js, icons, fonts) to build output.
//
// These are all referenced by ABSOLUTE path ("/favicon.svg", "/fonts/x.woff2").
// Vite does not bundle absolute-path assets and there is no publicDir here, so
// anything listed in index.html or CSS with a leading slash must be copied
// explicitly or it 404s in production. If you add an asset referenced that way,
// add it here too.
function copyStaticFiles() {
    const filesToCopy = [
        'sw.js',
        'manifest.json',
        // PWA + favicons, generated by scripts/generate-icons.js
        'icon-192.png',
        'icon-512.png',
        'icon-maskable-192.png',
        'icon-maskable-512.png',
        'apple-touch-icon.png',
        'favicon.svg',
        'favicon-32.png',
        'favicon-16.png'
    ];
    // Directories copied wholesale (self-hosted DM Sans).
    const dirsToCopy = ['fonts'];

    return {
        name: 'copy-static-files',
        writeBundle(options) {
            const outDir = options.dir || resolve(__dirname, '../src/public');
            const missing = [];

            for (const file of filesToCopy) {
                const src = resolve(__dirname, file);
                if (!fs.existsSync(src)) { missing.push(file); continue; }
                fs.copyFileSync(src, resolve(outDir, file));
            }

            for (const dir of dirsToCopy) {
                const src = resolve(__dirname, dir);
                if (!fs.existsSync(src)) { missing.push(dir + '/'); continue; }
                fs.cpSync(src, resolve(outDir, dir), { recursive: true });
            }

            const copied = filesToCopy.length + dirsToCopy.length - missing.length;
            console.log(`Copied ${copied} static asset(s) to build output`);
            if (missing.length) {
                // Loud, because a silent miss ships a build with dead icons.
                console.warn(`WARNING: static assets not found, NOT copied: ${missing.join(', ')}`);
            }
        }
    };
}

export default defineConfig({
    root: '.',
    base: '/',
    appType: 'mpa',

    server: {
        port: 5173,
        host: true,
        proxy: {
            // Proxy API requests to the backend
            '/api': {
                target: 'http://localhost:3000',
                changeOrigin: true,
                secure: false
            },
            // Proxy socket.io
            '/socket.io': {
                target: 'http://localhost:3000',
                ws: true
            },
            // Proxy static files
            '/covers': {
                target: 'http://localhost:3000',
                changeOrigin: true
            },
            '/downloads': {
                target: 'http://localhost:3000',
                changeOrigin: true
            }
        }
    },

    build: {
        outDir: '../src/public',
        emptyOutDir: true,
        rollupOptions: {
            input: {
                main: './index.html',
                login: './login.html'
            }
        }
    },

    plugins: [copyStaticFiles()]
});
