services:
  manga-reader:
    build: .
    container_name: manga-reader
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=1234
      - JWT_SECRET=change_this_to_a_long_random_string_12345
      - DATA_DIR=/app/data
      - DOWNLOADS_DIR=/app/downloads
      - CHROME_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      # Database and covers
      - /mnt/ApsonaterCloud/ApsonaterWinshare/Apps/manga/data:/app/data
      # Downloads/media
      - /mnt/ApsonaterCloud/ApsonaterWinshare/Apps/manga/media/downloads:/app/downloads
